### ISSUE TITLE
FRAMEWORK!!! 

### ISSUE THREAD

**Issue by mathcodes** [mathcodes/contentfordevelopers#109]
Things are kicking off and you guys are really pulling through. I really appreciate everything you have all done for this project. With that said, we have enough UI built to where we need to choose a 3rd party framework to use. It's not a requirement, but I'm kind of making it one for a couple of reasons: 

1. It makes development go SO much faster 
2. Keeps us all on the same page,
3. It is a tool that you will either learn or enhance your knowledge on :)

So. Let's take a vote! To submit your vote, just comment on this issue below. Only current contributors can vote. Not a contributor? No problem... read the [GUIDELINES.md](https://github.com/mathcodes/contentfordevelopers/blob/main/GUIDELINES.md) and join the team!!! It will take you 5 minutes to join (and if you need help contact [Jon](https://twitter.com/thejonchristie)!

Options are:

- MaterialUI
- Bulma
- react-bootstrap
- tailwindcss 
- Other (must suggest your choice)

I'm counting votes this Friday, Dec 23, 2022, at 5 pm. Get them in!!!

**Comment by jackz070** [comment]
For me personal preference out of those is tailwindcss, as I've had the most experience with it. I've also touched a bit of Bulma and MaterialUI, but they didn't really resonate with me. I believe all those can be tailored to style guidelines / theme. I would go with tailwind!

**Comment by GooferG** [comment]
I would vote for tailwindcss as well! I love their workflow and how easy it is to customize units and work with CSS this way.

**Comment by mathcodes** [comment]
Let's go with TailwindCSS. Thank you for the input... We can keep MUI in there for certain use cases, but let's keep that light as it can turn into a beast pretty quickly, lol. Right on. I'll create some issues to get this sorted out. I think it's time for some cleanup as there are many unused lines of code floating around.

Thanks again 👍
