### ISSUE TITLE
Revise README with updated photos to include all contributors. 

### ISSUE THREAD

**Issue by mathcodes** [mathcodes/contentfordevelopers#135]
SUPER EASY FOR FIRST TIMERS!!!!

**Comment by SandeepKrSuman** [comment]
Hey @mathcodes , looks like PR #137 uses manual way to show the photos of the contributors by inserting their profile urls. This is doing the work as of now but as the project will grow it will be cumbersome. I propose to do this using fewer lines of code that will get auto updated even if new contributors come later. I'm creating a PR in reference to this issue. Do take a look.
