### ISSUE TITLE
Internal Docs Style Guide

### ISSUE THREAD

**Issue by CBID2** [mathcodes/contentfordevelopers#166]
Hey @mathcodes! :) Have you considered having a style guide for the Docs on this repo? It'd be a great way for contributors to gain tech writing skills! :)

**Comment by mathcodes** [comment]
I have but haven't gotten around to it. It's becoming necessary though especially as we move forward, to clean up the unused code and strip down the dependencies to what we need and are using (mainly replacing MUI and SCSS with Tailwind and for the time being, getting Redux out of the mix (in my opinion). 

Great issue @CBID2... if you are you up for taking it on I can help out. Up to you... as of now its up for grabs!

**Comment by CBID2** [comment]
> I have but haven't gotten around to it. It's becoming necessary though especially as we move forward, to clean up the unused code and strip down the dependencies to what we need and are using (mainly replacing MUI and SCSS with Tailwind and for the time being, getting Redux out of the mix (in my opinion). 
> 
> 
> 
> Great issue @CBID2... if you are you up for taking it on I can help out. Up to you... as of now its up for grabs! 

I want to work on it @mathcode! :) I'm going to write it on a google Doc and then do my PR for your review. :)

**Comment by mathcodes** [comment]
Awesome! Love it @CBID2 👍

**Comment by CBID2** [comment]
> Awesome! Love it @CBID2 👍

Hi @mathcodes! Here's my for the style guide: https://github.com/mathcodes/contentfordevelopers/pull/167
