### ISSUE TITLE
[DOCS] Continue working on Style Guide

### ISSUE THREAD

**Issue by CBID2** [mathcodes/contentfordevelopers#168]
Per your suggestion in #167 and #166, let’s continue working on the style guide @mathcodes! 😊

**Comment by mathcodes** [comment]
Awesome, sounds good! Thank you :)

**Comment by CBID2** [comment]
> Awesome, sounds good! Thank you :) 

You're welcome @mathcodes! I'll do these parts:

Purpose of the Style Guide
Target Audience
Overview of Open Source Documentation
Documentation Principles

Accuracy and Precision
Clarity and Simplicity
Consistency
Accessibility
Inclusivity
Writing Style

Use plain language
Write in a concise and clear manner
Avoid jargon and technical terms when possible
Use active voice and present tense
Organize content logically and coherently
Structure and Formatting

Document structure (Introduction, Installation, Usage, etc.)
Use headings and subheadings consistently
Employ bullet points and numbered lists for clarity
Utilize tables, diagrams, and screenshots where necessary
Use code blocks and syntax highlighting for code examples
Language and Grammar

Spelling and grammar guidelines
Use of inclusive language
Consistent use of terminology

**Comment by mathcodes** [comment]
👍

**Comment by CBID2** [comment]
> Let use the branch 'feat-style-guide' to work on this until we merge with main. I have a draft that you can look over and edit 👍

Ok

**Comment by mathcodes** [comment]
I submitted a PR with a lot added as plain text for the time being. Let me know what you think as it needs examples for one. we don't need to merge it, we can just keep working in feat-style-guide until its complete. Thanks Chrissy!

**Comment by CBID2** [comment]
> @CBID2 I submitted a PR with a lot added as plain text for the time being. Let me know what you think as it needs examples for one. we don't need to merge it, we can just keep working in feat-style-guide until its complete. Thanks Chrissy!

Thanks @mathcodes! Can you link it here?

**Comment by CBID2** [comment]
> @CBID2 I submitted a PR with a lot added as plain text for the time being. Let me know what you think as it needs examples for one. we don't need to merge it, we can just keep working in feat-style-guide until its complete. Thanks Chrissy!

I didn't see that PR @mathcodes

**Comment by mathcodes** [comment]
Do you have a link to the PR you're talking about as I don't see any up atm.

**Comment by CBID2** [comment]
> Do you have a link to the PR you're talking about as I don't see any up atm.

No that’s your idea @mathcodes. :)
