### ISSUE TITLE
ISSUE SEPARATED INTO SEPARATE ISSUES!

### ISSUE THREAD

**Issue by mathcodes** [mathcodes/contentfordevelopers#76]
THIS ISSUE HAS BEEN SEPARATED INTO SEPARATE ISSUES. PLEASE REFER TO THOSE TO MAKE YOUR CONTRIBUTIONS TO THE UI. I WILL KEEP THIS OPEN FOR A LITTLE WHILE AS NOT TO CONFUSE ANYONE.

**Comment by zaahmed-nisum-com** [comment]
@mathcodes  Please assign this issue to me

**Comment by SwarnitSinha** [comment]
Hello @mathcodes, I want to work on this issue. I am new to open source but I know MERN development. So, please assign this issue to me.

**Comment by mathcodes** [comment]
Feel free to use the notes as a general idea to start with and adjust as needed! Thanks!

**Comment by mathcodes** [comment]
I would suggest doing this one step at a time so we can stay on the same page and also allow others to tackle some of the steps. Would it be better if I split up the issues into separate ones? How are things coming along on your end?

**Comment by SwarnitSinha** [comment]
@mathcodes I have started building the website. Built a basic structure for it. Now I will work on every component for better UI design. Should I make a merge request on every step?

**Comment by rootrsk** [comment]
Hey, @mathcodes  I wanted to improve the file tree structure and add redux to this project.

**Comment by mathcodes** [comment]
That sounds great. I have some other devs joining us soon to work on the UI, but this would be awesome. Let me know if you need anything from me.

**Comment by mathcodes** [comment]
So I see some adjustments that need to be made, which I will address by revising the checklist. Please feel free to submit PR for any item on the list or other ideas you have and would like to suggest.

**Comment by jackz070** [comment]
Hello! I'd like to take the footer task if it's still up for grabs no matter the checklist revision, but need clarification: is it supposed to contain only the license badge, or should it also have some text description of the license or a link to it?

**Comment by SwarnitSinha** [comment]
Yes @jackz070  you can work on the footer component. It will have some more details you can ask @mathcodes for more information.

**Comment by mathcodes** [comment]
@jackz070 - I've been trying to get around to that, so thanks for the reminder. BTW, I'm open to suggestions and input for anything we're putting together here!

I will create a new issue for the footer alone and actually separate out these issues into pieces as I should have in the first place. 

NOTE: Please read the GUIDELINES.md which is an evolving document to outline this project's standards, and also has the first contribution steps for onboarding new contributors. Thank you in advance 🙏
